<a href="https://colab.research.google.com/github/SnehaPradhan04/Sorting/blob/main/Numpy04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#sort, search and counting functions

import numpy as np
arr = np.array([94,33,74,15,6])
arr

array([94, 33, 74, 15,  6])

In [ ]:
np.sort(arr)

array([ 6, 15, 33, 74, 94])

In [ ]:
np.searchsorted(arr,7)

0

In [ ]:
arr1 = np.array([0,3,675,98,9,67,52,14,0,0,0])
np.count_nonzero(arr1)

7

In [ ]:
np.where(arr1 > 0)

(array([1, 2, 3, 4, 5, 6, 7]),)

In [ ]:
np.where(arr1 < 0)

(array([], dtype=int64),)

In [ ]:
np.extract(arr > 2, arr)

array([94, 33, 74, 15,  6])

In [ ]:
np.extract(arr1 > 2, arr1)

array([  3, 675,  98,   9,  67,  52,  14])

In [ ]:
#byte swapping
arr1

array([  0,   3, 675,  98,   9,  67,  52,  14,   0,   0,   0])

In [ ]:
arr.byteswap(True)

array([6773413839565225984, 2377900603251621888, 5332261958806667264,
       1080863910568919040,  432345564227567616])

In [ ]:
arr

array([6773413839565225984, 2377900603251621888, 5332261958806667264,
       1080863910568919040,  432345564227567616])

In [ ]:
#copies and views
a = np.copy(arr1)
b = arr1.view() #b=arr1
b

array([  0,   3, 675,  98,   9,  67,  52,  14,   0,   0,   0])

In [ ]:
b[0] = 6
b

array([  6,   3, 675,  98,   9,  67,  52,  14,   0,   0,   0])

In [ ]:
#matrix library
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(4) #identity matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#linear algebra
arr1

array([  6,   3, 675,  98,   9,  67,  52,  14,   0,   0,   0])

In [ ]:
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[5,3], [2,5]])


In [ ]:
arr1

array([[0, 2],
       [3, 3]])

In [ ]:
arr2

array([[3, 1],
       [0, 1]])

In [ ]:
np.dot(arr1,arr2)

array([[0, 2],
       [9, 6]])

In [ ]:
arr1@arr2

array([[0, 2],
       [9, 6]])